### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by tuyulbalap767** [Xtr126/XtMapper#149]
**Describe the issue**
Server crash whenever I want to start an app

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="720" height="1600" alt="Image" src="https://github.com/user-attachments/assets/630ffd2b-c67e-4e59-a419-de8566afabb8" />

**Device (please complete the following information):**
 - OS: XOS
 - Android version 14

**Comment by tuyulbalap767** [comment]
My phone Infinix smart 9

**Comment by Xtr126** [comment]
I fixed this sometime ago but didn't make a release yet. 
If you can please try the APK from here https://github.com/Xtr126/XtMapper/actions/runs/15735646422/job/44347514196 and see if works fine or not.
If it works fine we can close this as duplicate of https://github.com/Xtr126/XtMapper/issues/146

**Comment by tuyulbalap767** [comment]
Hello sorry for late reply, now when I want to launch an app it write "connecting to server" but I waited like 10 minutes and nothing happened.

**Comment by tuyulbalap767** [comment]
<img width="1600" height="720" alt="Image" src="https://github.com/user-attachments/assets/4d828a5f-d3ca-4e56-8ab1-010475de652d" />

**Comment by Xtr126** [comment]
Here's a document on how to activate it: https://xtr126.github.io/XtMapper-docs/guides/activation/
Well just install Shizuku and once you launch XtMapper you should see a dialog with what to do.

**Comment by tuyulbalap767** [comment]
I do the instructions on the apks but the problem still exist, and I'm testing it on my rootrd phone and it's the same.. always connecting to the server, or did I just missed something?

**Comment by Xtr126** [comment]
> I do the instructions on the apks but the problem still exist, and I'm testing it on my rootrd phone and it's the same.. always connecting to the server, or did I just missed something?

No, sorry I downloaded the same APK to try right now and encountered the same issue.

**Comment by Xtr126** [comment]
Now it doesn't show the false warning anymore. I didn't notice it initially because I had "Open editor as overlay" enabled.Thanks for reporting.

**Comment by tuananhnoobvn** [comment]
> I fixed this sometime ago but didn't make a release yet. If you can please try the APK from here https://github.com/Xtr126/XtMapper/actions/runs/15735646422/job/44347514196 and see if works fine or not. If it works fine we can close this as duplicate of [#146](https://github.com/Xtr126/XtMapper/issues/146)

Idk how to using the link. Can you explain this ?

**Comment by Xtr126** [comment]
> > I fixed this sometime ago but didn't make a release yet. If you can please try the APK from here https://github.com/Xtr126/XtMapper/actions/runs/15735646422/job/44347514196 and see if works fine or not. If it works fine we can close this as duplicate of [#146](https://github.com/Xtr126/XtMapper/issues/146)
> 
> Idk how to using the link. Can you explain this ?

You can click on a green tick in a commit or download latest APK from the actions tab.
Here's a link https://github.com/Xtr126/XtMapper/issues/149#issuecomment-3088209660
